### ISSUE TITLE
VBBot To-Do List

### ISSUE THREAD

**Issue by StupidDan** [TheMegaEagle/VBBot2#1]
Hey, I'm Dan or Dan#7528 from the VaronBros Discord server, and these are some of the things that I think need to be in VBBot.

- A command handler, so each command is in a separate file.
- The usage of ESLint, so the code is tidy and validated.
- `async` functions, so everything runs smoothly.
- Basic moderation commands. (kinda obvious but hey)
- An `eval` command so we can easily debug things if something goes wrong, this should only be able to be used by Eagle/Management.

That's all I can think of for now, if you have any questions about something I've listed, don't hesitate to drop me a DM or mention me on the VaronsBros Community Discord server. Happy coding. 😄

**Comment by StupidDan** [comment]
Turns out this is the wrong page, oof.

**Comment by TheMegaEagle** [comment]
async functions have been added, as well as command handler

**Comment by TheMegaEagle** [comment]
eval added

**Comment by Artuto** [comment]
This project was scraped.
